// --- 1. CONFIGURACIÓN DEL MAPA ---
var map = L.map('map').setView([14.65, -86.21], 13); // Coordenadas Juticalpa
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);

var marcador = L.marker([14.65, -86.21], {draggable: true}).addTo(map);

marcador.on('dragend', function() {
    var p = marcador.getLatLng();
    document.getElementById('coords').innerText = p.lat.toFixed(6) + ", " + p.lng.toFixed(6);
});

function obtenerGPS() {
    navigator.geolocation.getCurrentPosition(pos => {
        var p = [pos.coords.latitude, pos.coords.longitude];
        map.setView(p, 18);
        marcador.setLatLng(p);
        document.getElementById('coords').innerText = p[0].toFixed(6) + ", " + p[1].toFixed(6);
    });
}

// --- 2. NAVEGACIÓN ENTRE VISTAS ---
function mostrarSeccion(nombre) {
    document.getElementById('dashboard').style.display = 'none';
    document.getElementById('seccion-formulario').style.display = 'block';
    document.getElementById('titulo-actividad').innerText = nombre.toUpperCase();

    // Cargamos los materiales justo al abrir la sección
    cargarMateriales();

    // Esto "despierta" al mapa para que no salga gris
    setTimeout(() => { map.invalidateSize(); }, 300);
}

function volverAlInicio() {
    document.getElementById('dashboard').style.display = 'block';
    document.getElementById('seccion-formulario').style.display = 'none';
}

// --- 3. GESTIÓN DE MATERIALES (283 ÍTEMS) ---
const materiales = [
    "BLOQ MADER P/ CÁMAR DE INSPEC 10X50X10CM", "BORNERA BASE MED TRIF SOCKET CL.200 240V.",
    "BORNERA PARA CORRIENTE", "CONECTOR COMPR CABLE 1/0 - #2", "CONECTOR COMPR CABLE 1/0 A 1/0 TIPO C",
    "CONECT COMPR CABLE 3/0 Y 4/0 CON #2 - #6", "CONECTOR COMPRESION CABLE 3/0-1/0",
    "CONECT COMPR CABL 3/0 Y 4/0 DE 3/0 Y 4/0", "CONECTOR COMPR CABLE #2 - #2",
    "CONECT COMPR CABLE #2 CON #4", "CONECTOR COMPR CABLE1/0-2/0 CON #4 Y #6",
    "CONECTOR COMPR CABLE 2/0-3/0 CON #8 Y#14", "CONECTOR DE ESTRIBO CABLE 1/0-266.8 MCM",
    "CONECTOR DE ESTRIBO CABLE 3/0-556 MCM", "CONECTOR DE LÍNEA VIVA NO. 4/0",
    "CONECTOR DE PIN NO. 2", "CONECTOR DE PIN 1/0", "CONECTOR DE PIN 2/0",
    "CONECTOR DE PIN 266", "CONECTOR DE PIN 3/0", "CONECTOR DE PIN 4/0",
    "CONECTOR DE TENSIÓN PARA CABLE 3/0", "CONECTOR DE COMPRESIÓN DE 1/0 - 6 AWG",
    "CONECTOR DE TENSIÓN P/ CABLE 266.8 ACSR", "CONECTOR YC KDR 28",
    "CONECTOR CU 3/0 - 4/0 CON 3/0 - 4/0", "CONECTOR COMPRESION PARA CABLE 477 ACSR",
    "CONECTOR YC2A6", "CONECTOR DE TENSION PARA CABLE 1/0 ACSR",
    "CONECTOR DE LINEA VIVA 2-2/0", "CONECTOR COMPRESION HCRIPMP 4/0-477 ACSR",
    "CONECTOR DE LINEA VIVA 477", "CONECTOR DE TENSION P/CABLE 2",
    "CONECTOR COMPRESION T/PLANCHA CABLE 266", "CONECTOR COMPRESION T/PLANCHA CABLE 3/0",
    "CONECTOR COMPR AL TIP H #6#2 BURND YHO-1", "CONECTOR COMPRE T/PLANCHA CABLE 1/0",
    "CONECTOR DE COMPRESIÓN BIMET TIPO YHD-3", "CONECTOR DE ESTRIBO 4-4/0",
    "TERMINAL BORNE PARA SECUNDARIO", "PREFORMADO PARA LÍNEA 1/0 ACSR",
    "PREFORMADO PARA LÍNEA 266.8 ACSR", "PREFORMADO PARA LÍNEA 3/0 ACSR",
    "PREFORMADO PARA RETENIDA 1/4\"", "PREFORMADO PARA RETENIDA 3/8\"",
    "PREFORMADO PARA RETENIDA 5/16\"", "CONECTOR ANCLAJE DIELECTRICO/TIE OFF 1.8",
    "CUCHILLA 1P 600A 34.5 KV", "CUCHILLA BYPASS RBD 600A PARA 34.5 KV",
    "AISLADOR ESPIGA PARA 13.8 KV CLASE 55-4", "AISLADOR ESPIGA PARA 34.5 KV CLASE 56-3",
    "AISLADOR DE CARRETE 3-1/8\" CLASE 53-2", "AISLADOR DE SUSPENSION CLASE 52-9",
    "CINTA FLEJE METÁLICA DE 1/2 (ROLLO)", "AISLADOR TENSIÓN P/ RETENIDA CLASE 54-4",
    "CINTA AISLANTE 90° 1000V RETARDANTE", "AISLADOR TENSION P/RETENIDA CLASE 54-2",
    "CINTA AISLANTE SCOHT SUPER 33", "AISLADOR DE SUSPENSION CLASE 52-4",
    "AISLADOR TENSION P/RETENIDA CLASE 54-3", "AISLADOR DE SUSPENSION ANSI CLASE 52-3",
    "ALAMBRE DE ALUMINIO PARA AMARRE NO. 6", "CABLE BIMETÁLICO ALUM COBRIZ NO. 6",
    "CABLE ALUM DESNUDO NO. 1/0 ACSR", "CABLE ALUM DESNUDO NO. 2/0 ACSR",
    "CABLE ALUM DESNUDO NO. 2 ACSR", "CABLE ALUM DESNUDO NO. 3/0 ACSR",
    "CABLE ALUM DESN NO.266.8 ACSR PARTRIDGE", "CABLE PARA RETENIDA ACERADO 1/4\"",
    "CABLE PARA RETENIDA ACERADO 3/8\"", "CABLE PARA RETENIDA ACERADO 5/16\"",
    "CABLE TRIPLEX 2X3 NEUTRO DESNUDO", "CABLE NEUTRO DESNUDO TRIPLEX 3X6",
    "CABLE CBRE F 13 HIL CONT FOIL ALUM #12", "CABLE COBRE DESNUDO UL LISTED NO. 2",
    "CABLE ACERADO DE COBRE NO. 6", "CABLE DE COBRE SOLIDO #6",
    "CABLE CONTROL UL LISTED 6X12 AWG 600V", "CABLE ALUM FORRADO NO. 1/0 WP 75 600V",
    "CABLE ALUM FORRADO NO. 2 WP 75 600V", "CABLE ALUM FORRADO NO. 2/0 WP 75 600V",
    "CABLE ALUM FORRADO NO. 3/0 WP 75 600V", "CABLE ALUM FORRADO NO.266.8 75 600V",
    "CABLE COBRE FORRADO THHN 600V 91 NO. 14", "CABLE DE COBRE 600V THWN N6 AWG BLANCO",
    "CABLE ALUM DESNUDO #477 ACSR", "CABLE ALUM FORRADO NO. 4/0",
    "BASE MEDIDOR TIPO SOCKET 13 TERMINALES", "BOLSA CUSTODIA MEDIDOR",
    "TRANSFORMADO 100KVA 19.9/34.5KV-120/240V", "TRANSFORMADOR 15KVA 19.9/34.5KV-120/240V",
    "TRANSFORMADOR 25KVA19.9/34.5KV-120/240V", "TRANSFORMADR 37.5KVA 19.9/34.5KV-120/240",
    "TRANSFORMADOR 50KVA 19.9/34.5KV-120/240V", "TRANSFORMADOR 75KVA 19.9/34.5KV-120/240V",
    "TRAFO CTE400/5 208-240V EXT CL0.5S 5VA", "CORTACIRCUITO SENCILLO 15KV 100AMP 10KA",
    "CORTACIRCUITO ROMPEARCO 27KV 100AMP 12KA", "CORTACIRCUITO SENCILLO 27KV 100AMP 12KA",
    "DETECTOR AUSENCIA DE TENSIÓN MT", "PARARRAYO 27KV MET/OXI VAR MCOV22KV",
    "FUSIBLE ALTA TENSIÓN 0.5 A TIPO K", "FUSIBLES DE 1 A", "FUSIBLES DE 10 A",
    "FUSIBLES DE 100 A", "FUSIBLES DE 12 A", "FUSIBLES DE 15 A", "FUSIBLES DE 2 A",
    "FUSIBLES DE 20 A", "FUSIBLES DE 25 A", "FUSIBLES DE 3 A", "FUSIBLES DE 30 A",
    "FUSIBLES DE 4 A", "FUSIBLES DE 40 A", "FUSIBLES DE 5 A", "FUSIBLES DE 50 A",
    "FUSIBLES DE 6 A", "FUSIBLES DE 65 A", "FUSIBLES DE 8 A", "FUSIBLES DE 80 A",
    "BATERIAS DE 12 V, 12 AH", "TRANSFORMADOR 1KVA, 19,92/34,5-120V",
    "REGULADOR MONOFASE 833 KVA 19920/34500Y", "REGULADOR MONOFASE 500 KVA 19920/34500Y",
    "RESTAURADOR TRIFASICO 34.5KV (KIT)", "CINTA ACERO INOX UL LIST 3/4\" (FLEJE)",
    "PERNO GOLOSO 1/2X4\"", "HEBILLA ACERO INOX. PARA CINTA 3/4\"",
    "FAJILLA PLASTICA 18\"", "ARANDELAS DE 11X16", "PERNO DE ROSCA CORRIDA 5/8X10\"+4 TUERCA",
    "PERNO DE ROSCA CORRIDA 5/8X12\"+4 TUERCA", "PERNO DE ROSCA CORRIDA 5/8X14\"+4 TUERCA",
    "PERNO DE ROSCA CORRIDA 5/8X16\"+4 TUERCA", "PERNO DE ROSCA CORRIDA 5/8X18\"+4 TUERCA",
    "PERNO DE ROSCA CORRIDA 5/8X20\"+4 TUERCA", "PERNO DE ROSCA CORRIDA 5/8X22\"+4 TUERCA",
    "PERNO DE ROSCA CORRIDA 5/8X24\"+4 TUERCA", "PERNO CARRUAJE + TUERCA 3/8X5\"",
    "PERNO DE MÁQUINA +TUERCA DE 5/8X10\"", "PERNO DE MÁQUINA + TUERCA DE 5/8X12\"",
    "PERNO DE MÁQUINA + TUERCA DE 5/8X14\"", "PERNO DE MÁQUINA + TUERCA DE 5/8X16\"",
    "PERNO DE MÁQUINA + TUERCA DE 5/8X18\"", "PERNO DE MÁQUINA + TUERCA DE 5/8X20\"",
    "PERNO DE MÁQUINA + TUERCA DE 5/8X22\"", "TUERCA DE OJO 5/8\"", "ARANDELAS CUADRADAS DIA. 11\"/16\"",
    "PERNO CARRIAJE 1/4X6\"", "PERNO MAQUINA 1/2X10\"", "PERNO MAQUINA + TUERCA 5/8x8\"",
    "PERNO OJO CURVO + GUARDACABO 5/8X10\"", "PERNO OJO CURVO + GUARDACABO 5/8X12\"",
    "PERNO OJO TIPO OBAL 5/8X10\"", "PUNTAL ANGULAR 3/16X1 - 3/4X1 - 3/4X50\"",
    "PERNO ATERIZ CARCAZA TRAFO NO. 10-6", "PERNO DE OJO C/ESLABON 5/8X12\"",
    "HEBILLA ACERO INOX. PARA CINTA 1/2\"", "ARANDELA CUADRADA 2-1/4 x 2-1/4 x 2/16\"",
    "PERNO DE MAQUINA 1/2\"X6\" CABEZA CUADRADA", "CINTA SEGURIDAD PARA DEMARCAR 8CM ROLLO",
    "CONO SEÑALIZACIÓN 70cm", "ABRAZADERA AJUSTABLE 4 PERNOS 7-1/2X1/2\"",
    "ABRAZ SENC.6A 6-5/8,1/4X1-1/2 6366", "ABRAZADERA T/DADO P/POSTE DE 6X1/4X2\"",
    "ABRAZADERA PLETINA 6MM 180MM+ PERNO 5/8\"", "BASTIDOR GALVANIZADO PARA 1 LÍNEA",
    "BASTIDOR GALVANIZADO PARA 3 LÍNEAS", "BASTIDOR GALVANIZADO PARA 4 LÍNEAS",
    "BRAZO CORTO RETENIDA DE BCO.", "CRUCETE DE MADERA 4X5X48\"", "CRUCETE DE MADERA 4X5X96\"",
    "CRUCETE DE MADERA DE 4X5X120", "CRUCETE DE MADERA 5X6X240\"", "TIRANTE DE PLATINA 1-1/4X1/4X30\"",
    "ESPIGA CRUCET MAD 8 ROSCA 1-3/8 DIAM=3/4", "ESPIGA PNTA POST CURVAL=21 ROSCA1-3/8\"",
    "ESPIGA PUNTA POSTE ESCUADRA 34.5KV 1 3/8", "PERNO DE OJO CURVO 5/8X14\"",
    "PERNO DE OJO DE 5/8X10\"", "PERNO DE OJO DE 5/8X12\" (THIMBLEYE)",
    "PERNO DE OJO RECTO 5/8X14\"", "GRAPA SUSP CABLE GUARDA 1/4 - 5/16",
    "GRAPA PARA CERCO 1/4\"", "GRAPA LÍNEA VIVA CABLE 6-3/0 ACSR",
    "GRAPA TERMINAL LÍNEA RECT 1/0- 4/0 ACSR", "GRAPA TERMINAL LÍNEA RECT 266.8- 556 MCM",
    "GRAPA PARALELA PARA CABLE 3/0-556 MCM", "GUARDACABO ACERO CABLE RETENIDA 5/16\"",
    "GRAPA TERM ESCUADRA CONDUC 3/0-556 MCM", "PLATINA ESPAC CRUCETE MADERA 1/2X4X24\"",
    "PLATO GALVANIZADO PARA RETENIDA DE 16X16", "PLATO GALVANIZADO PARA RETENIDA DE 20X20",
    "PROTECTOR RETENIDA MET 7FT LAMINA CAL 18", "PUNTAL ANGULAR 3/16X1 - 3/4X1 - 3/4X60\"",
    "VARILLA ANCLAJE GALV 5/8\" X 7\"", "VARILLA ANCLAJE GALV 5/8\" X6\"",
    "VARILLA CB ATER ACER AIS CU 250MC 5/8X8", "ESTRIBO TIPO ESCOPETA # 4-4/0 ACSR",
    "GRAPA P/VARILLA POLO TIERRA", "TIRANTE ANGULAR AB CHANCE 60\"",
    "ESPIGA CRUCET MAD 8\" ROSCA 1-3/8\" 0=5/8\"", "ESPIGA CRUCET MAD 6\" ROSCA DE 1\" 0=5/8\"",
    "BASE + CABEZAL 2\" P/RETENIDA BANCO", "GRAPA TERMINAL TIPO ESCUADRA #2 A 3/0",
    "BUSHIG PRIMARIO TRAFO 34.5 KV", "ESPIGA PUNTA POSTE RECTA 34.5KV 1 L20\"",
    "GRAPA CONCRETO 9MM", "BUSHING SECUNDARIO TRANSFO 50KVA -75 KVA",
    "CRUCERO ANGULAR ACERO GALV.3X3X1/4X94\"", "ROTULA CORTA DE OJO P/ CADENA SUSP 80KN",
    "HORQUILLA BOLA P/ CADENA SUSPENSIO 133KN", "GRAPA PARA LINEA VIVA RANGO #8 SOL – 2/0",
    "GRAPA TERMINAL RECTO P/CABLE 1/4 MD 46-C", "CRUCETE DE FIBRA DE VIDRIO 96\"",
    "CORTADORA RATCH PARA CABLE 1/0-556 MCM", "MONTCARG 1TON ELEV1.7MT MGO ALUM 2014LB",
    "MONTCARG 3TON ELEV1.7MT MGO ALM2030.5LB", "SEGUETA CON MARCO AISLADA CON HOJAS",
    "BROCAS PARA BERBIQUI ½\", ¾\", 5/8\"", "CAJA PLASTICA DE HERRAMIENTAS 51X22X5CM",
    "MAQ COMPR HIDRA MANUAL #4/0 A 477 MCM", "FASIMETRO ALTA TENSION 13.8KV- 34KV",
    "DADO REMACHADORA Y35 U251 CABLE 266", "DADO REMACHADORA Y35 U317 CABLE 477",
    "DADO REMACHADORA Y35 U261 CABLE 556", "DADO REMACHADORA Y35 U-H-3",
    "DADO REMACHADORA Y35 U-D3-1 YP27AU4", "REFLECTOR PORTÁTIL LED",
    "POSTE CONCRETO VIB/CFU 45FT - 14M X750KG", "POSTE CONCRETO VIB/CFU 35FT-10.6M X450KG",
    "POSTE CONCRETO VIB/CFU 40FT - 12M X750KG", "POSTE CONCRETO VIB/CFU 30FT - 9M X450KG",
    "POSTE MADERA CLASE 5 30FT", "POSTE MADERA CLASE 4 35FT", "POSTE MADERA CLASE 4 40FT",
    "POSTE MADERA CLASE 4 45FT", "POSTE MET TUBULAR 4 SECC(45ft)X1000lb/F",
    "POSTE METALICO SECCIONADO 35FT X500LB/F", "POSTE METALICO SECCIONADO 40FT X750LB/F",
    "POSTE METALICO SECCIONADO 45FT X750LB/F", "POSTE METALICO SECCIONADO 45FT X1000LB/F",
    "POSTE METALICO SECCIONADO 30FT X500LB/F", "POSTE DE MADERA 50FT CLASE 4",
    "POSTE DE FIBRA DE VIDRIO 40 PIES", "POSTE FIBRA DE VIDRIO SECCIONADO 45 PIES",
    "POSTE DE MADERA CLASE 5 35FT", "CÁMARA DE FOTOGRAFÍA 10MP",
    "CONJ PUESTA A TIERRA DE MT (JGOS) COBRE", "CONECTOR ATERRIZAJE PARA TRANSFORMADOR",
    "TRAFO URE 37.5KVA 19.9/34.5KV 120/240V", "TRAFO URE 50KVA 19.9/34.5KV 120/240V",
    "TRAFO URE 75kVA 19.9/34.5kV 120/240V", "CABLE ALUM DESNUDO NO. 2 ACSR URE",
    "POSTE CONCRETO 15M (50FT) URE", "CABLE ALUM FORRADO NO. 3/0 WP ENEE",
    "CRUCETE DE MADERA 4X5X96\" ENEE", "ESPIGA CRUCET MAD 8 ROSCA 1-1/8 ENEE",
    "GRAPA TERM LÍNEA RECT 1/0- 4/0 ACSR ENEE", "TIRANTE DE PLATINA 1-1/4X1/4X30\" ENEE",
    "CABLE ALUM DESNUDO NO. 1/0 ACSR URE", "ARANDELA CUADRADA 2-1/4X2-1/4X2/16\" PNRP",
    "ABRAZ SENC.6A 6-5/8,1/4X1-1/2 6366 ENEE", "CRUCETE DE MADERA 4X5X120\" ENEE",
    "CABLE ALUM DESN NO.556,5 ACSR EAGLE ENEE", "BASTIDOR GALVANIZADO PARA 1 LÍNEA ENEE",
    "CABLE NEUTRO DESNUDO TRIPLEX 3X6 ENEE", "POSTE METALICO SECCION 30T X500LB/F ENEE",
    "POSTE METALICO SECCION 35 X500LB/F ENEE", "POSTE METALICO SECCION 40 X500LB/F ENEE",
    "POSTE METALICO SECCION 45X500LB/F ENEE", "CABLE ACOMETIDA CONCÉNTRICA 2X6 ENEE",
    "CRUCETE DE MADERA 4X5X48\" ENEE", "CORTACIRCUITO SENCILLO 27KV 100AMP ENEE",
    "POSTE MADERA CLASE 4 35FT URE", "PREFORMADO PARA RETENIDA 1/4\" ENEE",
    "CRUCETE DE MADERA 5X6X240\" ENEE", "POSTE CONCRETO VIB/CFU 35FT - 10M ENEE",
    "VARILLA CB ATER ACER CU 250MC 5/8X8 ENEE", "POSTE MADERA CLASE 5 30FT URE",
    "CRUCETE METALICO 96\" ENEE", "CRUCETE METALICO 120\" ENEE",
    "ESPIGA PARA CRUCETE METALICO 34.5 ENEE"
];

function cargarMateriales() {
    const select = document.getElementById('lista-materiales');
    if(!select) return;
    select.innerHTML = "";
    materiales.forEach(m => {
        let opt = document.createElement('option');
        opt.value = m;
        opt.innerHTML = m;
        select.appendChild(opt);
    });
}

function filtrarMateriales() {
    const texto = document.getElementById('buscar-material').value.toLowerCase();
    const select = document.getElementById('lista-materiales');
    select.innerHTML = "";

    const filtrados = materiales.filter(m => m.toLowerCase().includes(texto));

    filtrados.forEach(m => {
        let opt = document.createElement('option');
        opt.value = m;
        opt.innerHTML = m;
        select.appendChild(opt);
    });
}

// --- 4. EXPORTACIÓN A PDF ---
function generarReporte() {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("REPORTE DE CAMPO - SECTOR JUTICALPA", 10, 20);

    doc.setFontSize(12);
    doc.text("Circuito: " + document.getElementById('circuito').value, 10, 40);
    doc.text("Actividad: " + document.getElementById('titulo-actividad').innerText, 10, 50);
    doc.text("Coordenadas: " + document.getElementById('coords').innerText, 10, 60);

    const matSeleccionado = document.getElementById('lista-materiales').value;
    doc.text("Material: " + (matSeleccionado || "No seleccionado"), 10, 70);

    doc.text("Observaciones:", 10, 80);
    doc.text(document.getElementById('obs').value, 10, 90);

    doc.save("Reporte_Juticalpa.pdf");
}

function cambiarEstado(btn) {
    document.querySelectorAll('.status-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
}
